apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secure-perimeter
resources:
  - namespace.yaml
  - kata-runtime-class.yaml
  - kyverno-policy.yaml
  - pvc-encrypted.yaml
  - workload.yaml
