apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-data
  namespace: secure-perimeter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-luks
  resources:
    requests:
      storage: 10Gi
